#!/bin/bash

#Yaes

usage="prm [option] [args]"

if [ "$#" -lt 1 ]; then
	printf "%s\n" "Incorrect Usage."
	printf "%s\n" "$usage"
	printf "%s\n" "Type 'prm h' to learn more"
else
	if [ "$1" = "h" ]; then
		#Nothing specified with help
		if [ "$#" -eq 1 ]; then
			printf "%s\n" "prm is a script to wrap together installation, compiling, and execution of different programs." "This is the Help Menu." "Usage: prm h [--c] [--h] [--i] [--r] [--s] [--t] [--init]"
		fi
		#Argument with h command
		if [ "$#" -ge 2 ]; then
			for arg in "$@"; do
				case $arg in
					prm)
						shift;;
					h)
						shift;;
					--h) 
						printf "%s\n" "'prm h' will display the help menu."
						shift;;
					--i) 
						printf "%s\n" "'prm i' installs different languages."
						shift;;
					--c)
						printf "%s\n" "'prm c' compiles files." "Usage: prm c [lang] [name] [source] [name] [source] [name] [source] ... "
						shift;;
					--r)
						printf "%s\n" "'prm r' runs programs." "Usage: prm r [lang] [(based on lang) version] [filename]"
						shift;;
					--s)
						printf "%s\n" "'prm s' views all saved compilers, interpreters, and packages."
						shift;;
					--t)
						printf "%s\n" "'prm t' transpiles from one language to another language."
						shift;;
					--init)
						printf "%s\n" "Initializes language management of prm by moving all external languages into a special folder and exporting that path."
						shift;;
					*) 
						printf "%s\n" "That argument does not exist."
						shift;;
				esac
			done
		fi
	elif [ "$1" = "c" ]; then
		#Compiling
		if [ "$#" -ge 3 ]; then
			#COMPILING FOR LANGUAGES
			if [ "$2" == 'C' -o "$2" == 'c' ]; then
				#C lang
				if [ $((($#) % 2)) -eq 0 ]; then
					for args in $(seq 3 2 $#); do
						aone=$(($args+1))
						text="gcc -o "${!args}" "${!aone}
						$text
					done
				else
					printf "%s\n" "A name and source file is necessary for each compile. "
				fi
			fi
		else
			printf "%s\n" "Usage: prm c [lang] [name] [source] [name] [source ...]"
			exit
		fi
	elif [ "$1" = "r" ]; then
		#Running
		if [ "$#" -ge 3 ]; then
			#RUNNING FOR LANGUAGES
			if [ "$#" -gt 3 ]; then
				if [ "$2" == 'python' ]; then
					text="python$3 $4"
					for args in $(seq 4 $#); do
						text=$text" "$args
					done
					$text
				fi
			else
				if [ "$2" == 'x' ]; then
					if [ -e $3 ]; then
						text="./"$3
						for args in $(seq 3 $#); do
							text=$text" "$args
						done
						$text
					else
						printf "%s\n" "That file does not exist. "
					fi
				elif [ "$2" == 'ruby' ]; then
					if [ -e $3 ]; then
						text="ruby "$3
						for args in $(seq 3 $#); do
							text=$text" "$args
						done
						$text
					else
						printf "%s\n" "That file does not exist. "
					fi
				fi
			fi
		else
			printf "%s\n" "Usage: prm r [lang] [(based on lang) version] [filename] [args]"
		fi
	fi
fi
